-- Auto-create siswa row at signup so tagihan trigger fires immediately
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  _nama text;
  _jenjang text;
  _jk text;
BEGIN
  _nama := COALESCE(NEW.raw_user_meta_data->>'nama', NEW.email);
  _jenjang := COALESCE(NEW.raw_user_meta_data->>'jenjang', 'SD');
  _jk := COALESCE(NEW.raw_user_meta_data->>'jenis_kelamin', 'L');

  INSERT INTO public.profiles (id, nama, email)
  VALUES (NEW.id, _nama, NEW.email)
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'siswa')
  ON CONFLICT (user_id, role) DO NOTHING;

  -- Create siswa shell so registration tagihan is generated by trigger
  BEGIN
    INSERT INTO public.siswa (
      user_id, nama_lengkap, email, jenjang, jenis_kelamin, status_akun
    ) VALUES (
      NEW.id, _nama, NEW.email,
      _jenjang::jenjang_type, _jk::jenis_kelamin, 'aktif'::status_akun
    )
    ON CONFLICT (user_id) DO NOTHING;
  EXCEPTION WHEN OTHERS THEN
    -- kuota penuh atau invalid, biarkan user signup; siswa bisa diisi nanti
    NULL;
  END;

  RETURN NEW;
END $$;